service: ahimmoyak-auth-service

provider:
    name: aws
    runtime: nodejs20.x
    stage: ${opt:stage, 'dev'}
    region: ap-northeast-2
    environment:
        COGNITO_CLIENT_ID: ${env:COGNITO_CLIENT_ID}
        COGNITO_USER_POOL_ID: ${env:COGNITO_USER_POOL_ID} # Cognito 사용자 풀 ID
        GOOGLE_CLIENT_ID: ${env:GOOGLE_CLIENT_ID}
        GOOGLE_CLIENT_SECRET: ${env:GOOGLE_CLIENT_SECRET} # Google 클라이언트 시크릿
    iamRoleStatements:
        - Effect: Allow
          Action:
              - cognito-idp:* # Cognito Identity Provider 서비스에 대한 모든 액션 허용
          Resource: "*"

functions:
    signup:
        handler: src/handlers/signup.handler
        events:
            - http:
                  path: signup
                  method: post
                  cors:
                      origin: "*" # 허용할 오리진
                      headers: # 허용할 헤더
                          - Content-Type
                          - Authorization
                      allowCredentials: true # 자격 증명 허용 (쿠키, 인증 헤더)

plugins:
    - serverless-plugin-dotenv
    - serverless-offline
